spring:
  application:
    name: book library
logging:
  level:
    ROOT: INFO
    strata: DEBUG
    gaia: DEBUG

---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS \"public\"
    driver: org.h2.Driver
    username: analytics
    password: password